// Mocks generated by Mockito 5.4.6 from annotations
// in pokedex_joash/test/widgets/pokemon_list_view_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:flutter/material.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:pokedex_joash/controllers/pokemon_controller.dart' as _i2;
import 'package:pokedex_joash/models/pokemon.dart' as _i3;
import 'package:pokedex_joash/models/user.dart' as _i5;
import 'package:pokedex_joash/providers/theme_provider.dart' as _i8;
import 'package:pokedex_joash/services/pokemon_sound.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PokemonController].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonController extends _i1.Mock implements _i2.PokemonController {
  MockPokemonController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.PokemonListItem> get pokemonList =>
      (super.noSuchMethod(
            Invocation.getter(#pokemonList),
            returnValue: <_i3.PokemonListItem>[],
          )
          as List<_i3.PokemonListItem>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasMore =>
      (super.noSuchMethod(Invocation.getter(#hasMore), returnValue: false)
          as bool);

  @override
  bool get isLoadingMore =>
      (super.noSuchMethod(Invocation.getter(#isLoadingMore), returnValue: false)
          as bool);

  @override
  String get searchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#searchQuery),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#searchQuery),
            ),
          )
          as String);

  @override
  List<_i3.PokemonListItem> get searchResults =>
      (super.noSuchMethod(
            Invocation.getter(#searchResults),
            returnValue: <_i3.PokemonListItem>[],
          )
          as List<_i3.PokemonListItem>);

  @override
  bool get isSearching =>
      (super.noSuchMethod(Invocation.getter(#isSearching), returnValue: false)
          as bool);

  @override
  bool get showingFavoritesOnly =>
      (super.noSuchMethod(
            Invocation.getter(#showingFavoritesOnly),
            returnValue: false,
          )
          as bool);

  @override
  List<_i3.PokemonListItem> get displayList =>
      (super.noSuchMethod(
            Invocation.getter(#displayList),
            returnValue: <_i3.PokemonListItem>[],
          )
          as List<_i3.PokemonListItem>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setUser(_i5.User? user) => super.noSuchMethod(
    Invocation.method(#setUser, [user]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> loadUserData() =>
      (super.noSuchMethod(
            Invocation.method(#loadUserData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  bool isFavorite(int? pokemonId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [pokemonId]),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<bool> toggleFavorite(int? pokemonId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [pokemonId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void toggleFavoritesFilter() => super.noSuchMethod(
    Invocation.method(#toggleFavoritesFilter, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> fetchPokemonList() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPokemonList, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> loadMorePokemon() =>
      (super.noSuchMethod(
            Invocation.method(#loadMorePokemon, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> searchPokemon(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPokemon, [query]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void clearSearch() => super.noSuchMethod(
    Invocation.method(#clearSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> selectPokemon(int? pokemonId) =>
      (super.noSuchMethod(
            Invocation.method(#selectPokemon, [pokemonId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void clearSelectedPokemon() => super.noSuchMethod(
    Invocation.method(#clearSelectedPokemon, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ThemeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeProvider extends _i1.Mock implements _i8.ThemeProvider {
  MockThemeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.ThemeMode get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i9.ThemeMode.system,
          )
          as _i9.ThemeMode);

  @override
  bool get isDarkMode =>
      (super.noSuchMethod(Invocation.getter(#isDarkMode), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> setThemeMode(_i9.ThemeMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeMode, [mode]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void toggleTheme() => super.noSuchMethod(
    Invocation.method(#toggleTheme, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AudioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioService extends _i1.Mock implements _i10.AudioService {
  MockAudioService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isMusicPlaying =>
      (super.noSuchMethod(
            Invocation.getter(#isMusicPlaying),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<void> playPokemonSound(int? pokemonId) =>
      (super.noSuchMethod(
            Invocation.method(#playPokemonSound, [pokemonId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> playThemeSong() =>
      (super.noSuchMethod(
            Invocation.method(#playThemeSong, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> pauseThemeSong() =>
      (super.noSuchMethod(
            Invocation.method(#pauseThemeSong, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resumeThemeSong() =>
      (super.noSuchMethod(
            Invocation.method(#resumeThemeSong, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> stopThemeSong() =>
      (super.noSuchMethod(
            Invocation.method(#stopThemeSong, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
